/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

/**
 *
 * @author ramon
 */
public class BasicCalc extends javax.swing.JFrame {

    /**
     * Creates new form BasicCalc
     */
    public BasicCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        number1 = new javax.swing.JSpinner();
        absoluto = new javax.swing.JLabel();
        number2 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        multi = new javax.swing.JLabel();
        calcButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resto2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cubo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        raiz = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        divisao = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cubica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        absoluto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        absoluto.setForeground(new java.awt.Color(0, 0, 153));
        absoluto.setText("0");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Digite outro valor:");

        multi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        multi.setForeground(new java.awt.Color(0, 0, 153));
        multi.setText("0");

        calcButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calc.png"))); // NOI18N
        calcButton.setText("Calcular");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Resto de divisão por 2");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Elevado ao cubo");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Raiz quadrada");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Raiz cubica");

        resto2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resto2.setForeground(new java.awt.Color(0, 0, 153));
        resto2.setText("0");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Valor absoluto");

        cubo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cubo.setForeground(new java.awt.Color(0, 0, 153));
        cubo.setText("0");

        jLabel7.setText("1 divido pelo 2");

        raiz.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        raiz.setForeground(new java.awt.Color(0, 0, 153));
        raiz.setText("0");

        jLabel8.setText("1 vezes 2");

        divisao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        divisao.setForeground(new java.awt.Color(0, 0, 153));
        divisao.setText("0");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Digite um valor:");

        cubica.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cubica.setForeground(new java.awt.Color(0, 0, 153));
        cubica.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 536, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cubo)
                    .addComponent(raiz)
                    .addComponent(cubica)
                    .addComponent(absoluto)
                    .addComponent(divisao)
                    .addComponent(multi)
                    .addComponent(resto2))
                .addGap(28, 28, 28)
                .addComponent(calcButton)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(number1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calcButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cubo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(raiz)
                        .addGap(18, 18, 18)
                        .addComponent(cubica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(absoluto)
                        .addGap(18, 18, 18)
                        .addComponent(divisao)
                        .addGap(18, 18, 18)
                        .addComponent(multi)
                        .addGap(53, 53, 53)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        int typednumber1 = Integer.parseInt(number1.getValue().toString());
        int typednumber2 = Integer.parseInt(number2.getValue().toString());
        
        /*Resto de divisão por 2*/
        int resto2Result = typednumber1 %2;
        resto2.setText(Integer.toString(resto2Result)); 
        /*Resto de divisão por 2*/

                
        /*Elevado ao cubo*/
        double cuboResult = Math.pow(typednumber1,2);
        cubo.setText(Double.toString(cuboResult)); 
        /*Elevado ao cubo*/
        
               
        
        /*Raiz quadrada*/
        double raizResult = Math.sqrt(typednumber1);
        raiz.setText(Double.toString(raizResult)); 
        /*Raiz quadrada*/
        
        
        /*Raiz cubica*/
        double cubicaResult = Math.cbrt(typednumber1);
        cubica.setText(Double.toString(cubicaResult)); 
        /*Raiz cubica*/
        
        
        /*Valor absoluto*/
        double absolutoResult = Math.abs(typednumber1);
        absoluto.setText(Double.toString(absolutoResult)); 
        /*Valor absoluto*/         
                
        /*1 divido pelo 2*/
        int dividido = typednumber1 / typednumber2;
        divisao.setText(Double.toString(dividido));
        /*1 divido pelo 2*/ 
        
        /*1 vezes 2*/
        int vezesResult = typednumber1 * typednumber2;
        multi.setText(Double.toString(vezesResult));
        /*1 vezes 2*/    
              
        
        // TODO add your handling code here:
    }//GEN-LAST:event_calcButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasicCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel absoluto;
    private javax.swing.JButton calcButton;
    private javax.swing.JLabel cubica;
    private javax.swing.JLabel cubo;
    private javax.swing.JLabel divisao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel multi;
    private javax.swing.JSpinner number1;
    private javax.swing.JSpinner number2;
    private javax.swing.JLabel raiz;
    private javax.swing.JLabel resto2;
    // End of variables declaration//GEN-END:variables
}
